language: emacs-lisp
sudo: no
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install "$EVM_EMACS" --use --skip
script:
  - make test
notifications:
  slack:
    secure: YxJhJnJMVZzDruAqOigEvL10XRD/ghYdsIjzXX3InrrW3JgYKVxb1no/5TkRcM9B1oWctH5ZkRST9wdaMKo9gnRWVaJBhtxazg/QEKv+n7kTSMtrtGAO71KZ2jFuNhn22hryJCNJB5laWBCzNxNelWEgS0Q7+HnuRED1GTcairM=
